apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: ibmcpd-cr
spec:
  license:
    accept: true
    license: Enterprise
  storageClass: ibmc-block-gold
  zenCoreMetadbStorageClass: ibmc-block-gold
  version: "4.0.1"